# Generated by Django 5.1.6 on 2025-02-15 13:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tracks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=1000, null=True)),
                ("album", models.CharField(blank=True, max_length=1000, null=True)),
                ("release_year", models.IntegerField(blank=True, null=True)),
                ("duration", models.IntegerField(blank=True, null=True)),
                (
                    "categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=100),
                        null=True,
                        size=10,
                    ),
                ),
                (
                    "composers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=100),
                        null=True,
                        size=10,
                    ),
                ),
                (
                    "singers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=100),
                        null=True,
                        size=10,
                    ),
                ),
                (
                    "writers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=100),
                        null=True,
                        size=10,
                    ),
                ),
                (
                    "actors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=100),
                        null=True,
                        size=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("lyrics_en", models.TextField(blank=True, null=True)),
                ("lyrics_hi", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
