# Generated by Django 5.1.6 on 2025-02-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tracks",
            old_name="title",
            new_name="title_en",
        ),
    ]
